config/routes.rb
Introuble::Application.routes.draw do
  resources :txtalerts

  resources :alerts
  
  get "home/index"

  devise_for :users, :controllers => { :registrations => "users" }
  devise_scope :user do
    resources :users
  end

  resources :users

  
  root :to => "home#index" 

  get 'manage' => "manage#index"
  get 'addalert' => "addalert#index"
  get 'about' => "about#index"
  get 'contact' => "contact#index"
  get 'developers' => "developers#index"
  get 'tos' => "tos#index"

end

app/models/txtalert.rb
class Txtalert < ActiveRecord::Base
    belongs_to :user
    before_save :addtimezone

    private
    def addtimezone 
      #find current user
      cuser = User.where(:id => self.user_id)
      #get the timezone of current user
      cuserutc = cuser.first.timezone[4..9]
      #construct string with time_alert + current timezone
      utimeconstruct = "#{self.time_alert} #{cuserutc}"
      #populate unixTime column (so we can compare it quickly when we scan database)
      self.unixtime = Time.parse(utimeconstruct)
    end
end

app/controllers/txtalerts_controller.rb
class TxtalertsController < ApplicationController
  before_action :set_txtalert, only: [:show, :edit, :update, :destroy]

  # GET /txtalerts
  # GET /txtalerts.json
  def index
    @txtalerts = Txtalert.all
  end

  # GET /txtalerts/1
  # GET /txtalerts/1.json
  def show
  end

  # GET /txtalerts/new
  def new
    @txtalert = Txtalert.new
  end

  # GET /txtalerts/1/edit
  def edit
  end

  # POST /txtalerts
  # POST /txtalerts.json
  def create
    @txtalert = Txtalert.new(txtalert_params)

    respond_to do |format|
      if @txtalert.save
        format.html { redirect_to @txtalert, notice: 'Txtalert was successfully created.' }
        format.json { render action: 'show', status: :created, location: @txtalert }
      else
        format.html { render action: 'new' }
        format.json { render json: @txtalert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /txtalerts/1
  # PATCH/PUT /txtalerts/1.json
  def update
    respond_to do |format|
      if @txtalert.update(txtalert_params)
        format.html { redirect_to @txtalert, notice: 'Txtalert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @txtalert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /txtalerts/1
  # DELETE /txtalerts/1.json
  def destroy
    @txtalert.destroy
    respond_to do |format|
      format.html { redirect_to txtalerts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_txtalert
      @txtalert = Txtalert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def txtalert_params
      params.require(:txtalert).permit(:time_alert, :contents, :to_sms, :user_id, :msg_sent)
    end
end

app/helpers/txtalerts_helper.rb
module TxtalertsHelper
end

app/views/txtalerts/_form.html.erb
<%= form_for @txtalert, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :time_alert, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :time_alert, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :contents, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :contents, :class => 'text_field' %>

    </div>
  </div>
  <div class="control-group">
    <%= f.label :to_sms, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :to_sms, :class => 'text_field' %>
    </div>
  </div>
  

  <div class="form-actions">
    <%= f.submit "Update", :class => 'btn btn-success' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                manage_path, :class => 'btn btn-danger' %>
  </div>
<% end %>

app/views/txtalerts/edit.html.erb
<h1>Edit Alert</h1>

<% if current_user.id == @txtalert.user_id %>
<%= render 'form' %>

<%= link_to 'Show', @txtalert %> 
<%= link_to 'Back', txtalerts_path %>
<% else %>
<strong>You do not have access to this page </strong>
<% end %>

app/views/txtalerts/index.html.erb
<h1>Listing txtalerts</h1>

<table>
  <thead>
    <tr>
      <th>Time alert</th>
      <th>Contents</th>
      <th>To sms</th>
      <th>User</th>
      <th>Msg sent</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @txtalerts.each do |txtalert| %>
      <tr>
        <td><%= txtalert.time_alert %></td>
        <td><%= txtalert.contents %></td>
        <td><%= txtalert.to_sms %></td>
        <td><%= txtalert.user_id %></td>
        <td><%= txtalert.msg_sent %></td>
        <td><%= link_to 'Show', txtalert %></td>
        <td><%= link_to 'Edit', edit_txtalert_path(txtalert) %></td>
        <td><%= button_to "Destroy", alert, :method => :delete, data: { confirm: 'Are you sure?' }%> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Txtalert', new_txtalert_path %>

app/views/txtalerts/new.html.erb
<h1>New txtalert</h1>

<%= render 'form' %>

<%= link_to 'Back', txtalerts_path %>

app/views/txtalerts/show.html.erb
<%- model_class = Txtalert -%>
<div class="page-header">
  <h1>Alert Recorded</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:time_alert) %>:</strong></dt>
  <dd><%= @txtalert.time_alert %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contents) %>:</strong></dt>
  <dd><%= @txtalert.contents %></dd>
  <dt><strong><%= model_class.human_attribute_name(:to_sms) %>:</strong></dt>
  <dd><%= @txtalert.to_sms %></dd>

</dl>

<div class="form-actions">
<%= link_to 'Back', manage_path, :class => 'btn btn-success' %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_txtalert_path(@txtalert), :class => 'btn btn-warning' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              txtalert_path(@txtalert),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>