config/routes.rb
Introuble::Application.routes.draw do
  resources :txtalerts

  resources :alerts
  
  get "home/index"

  devise_for :users, :controllers => { :registrations => "users" }
  devise_scope :user do
    resources :users
  end

  resources :users

  
  root :to => "home#index" 

  get 'manage' => "manage#index"
  get 'addalert' => "addalert#index"
  get 'about' => "about#index"
  get 'contact' => "contact#index"
  get 'developers' => "developers#index"
  get 'tos' => "tos#index"

end

app/models/smsalert.rb
class Smsalert < ActiveRecord::Base
    belongs_to :user
end

app/controllers/smsalerts_controller.rb
class SmsalertsController < ApplicationController
  before_action :set_alert, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user! 

  # GET /alerts
  # GET /alerts.json
  def index
    
    if user_signed_in? 
      @alerts = Smsalert.where(user_id: current_user)
    else
      @alerts = []
    end

  end

  # GET /alerts/1
  # GET /alerts/1.json
  def show
  end

  # GET /alerts/new
  def new
    @smsalert = Smsalert.new
  end

  # GET /alerts/1/edit
  def edit
  end

  # POST /alerts
  # POST /alerts.json
  def create
    @smsalert = Smsalert.new(alert_params)

    respond_to do |format|
      if @smsalert.save
        format.html { redirect_to @smsalert, notice: 'Smsalert was successfully created.' }
        format.json { render action: 'show', status: :created, location: @smsalert }
      else
        format.html { render action: 'new' }
        format.json { render json: @smsalert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1
  # PATCH/PUT /alerts/1.json
  def update
    respond_to do |format|
      if @smsalert.update(alert_params)
        format.html { redirect_to @smsalert, notice: 'Smsalert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @smsalert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @smsalert.destroy
    respond_to do |format|
      format.html { redirect_to alerts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @smsalert = Smsalert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params.require(:smsalert).permit(:time_alert, :contents, :to_email, :user_id, :msg_sent)
    end
end

app/views/smsalerts/_form.html.erb
<%= form_for(@alert) do |f| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
      <% @alert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time_alert %><br>
    <%= f.text_field :time_alert, class: "time_alert" %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_area :contents %>
  </div>
  <div class="field">
    <%= f.label :to_email %><br>
    <%= f.text_field :to_email %>
  </div>
  <div class="field">
  <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
  <%= f.hidden_field :msg_sent, :value => 'f' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/smsalerts/edit.html.erb
<h1>Editing smsalert</h1>

<% if current_user.id == @smsalert.user_id %>
<%= render 'form' %>

<%= link_to 'Show', @smsalert %> |
<%= link_to 'Back', smsalerts_path %>
<% else %>
<strong>You do not have access to this page </strong>
<% end %>

app/views/smsalerts/index.html.erb
<h1>Listing alerts</h1>


<table>
  <thead>
    <tr>
      <th>Time alert</th>
      <th>Contents</th>
      <th>To email</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  
    <% @alerts.each do |alert| %>
      <tr>
        <td><%= alert.time_alert %></td>
        <td><%= alert.contents %></td>
        <td><%= alert.to_email %></td>
        <td><%= alert.user_id %></td>
        <td><%= link_to 'Show', alert %></td>
        <td><%= link_to 'Edit', edit_alert_path(alert) %></td>
        <td><%= button_to "Destroy", alert, :method => :delete, data: { confirm: 'Are you sure?' }%> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alert', new_alert_path %>

app/views/smsalerts/new.html.erb
<h1>New alert</h1>

<%= render 'form' %>

<%= link_to 'Back', alerts_path %>

app/views/smsalerts/show.html.erb
<p>

<% if @alert.user_id == current_user.id %>
  <strong>Time alert:</strong>
  <%= @alert.time_alert %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @alert.contents %>
</p>

<p>
  <strong>To email:</strong>
  <%= @alert.to_email %>
</p>


<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>
<% else %>
<strong> You do not have access to this page <strong>
<% end %>