config/routes.rb
Introuble::Application.routes.draw do
  resources :txtalerts

  resources :alerts
  
  get "home/index"

  devise_for :users, :controllers => { :registrations => "users" }
  devise_scope :user do
    resources :users
  end

  resources :users

  
  root :to => "home#index" 

  get 'manage' => "manage#index"
  get 'addalert' => "addalert#index"
  get 'about' => "about#index"
  get 'contact' => "contact#index"
  get 'developers' => "developers#index"
  get 'tos' => "tos#index"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  <div class=botlink>
    © 2014 ditch.io
    <%= link_to "Contact", contact_path %> |
    <%= link_to "Developers", developers_path %>
    </div>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/ico/favicon.png">

    <title>ditch.io - Send Delayed Messages</title>
    <%= javascript_include_tag "jquery" %>

</script>
   <%= csrf_meta_tags %>
   <%= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track" => true %>
    <!-- Bootstrap core CSS -->
   <%= javascript_include_tag "application","data-turbolinks-track" => true %>
 <%= javascript_include_tag "application","data-turbolinks-track" => true %>
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="assets/javascripts/html5shiv.js"></script>
      <script src="assets/javascripts/respond.min.js"></script>
    <![endif]-->
  </head>

  <body data-spy="scroll" data-offset="0" data-target="#theMenu">
    
  <!-- Menu -->
  <nav class="menu" id="theMenu">
    <div class="menu-wrap">
      <h1 class="logo"><a href="http://ditch.io">ditch.io</a></h1>
      <i class="icon-remove menu-close"></i>
      <%= link_to "Home", root_path %>
      <%= link_to "About", about_path %>
      <%= link_to "Contact", contact_path %>
      <% if user_signed_in? %>
        <%= link_to "Settings", edit_user_registration_path %>
      <% end %>
     
    </div>
    
    <!-- Menu button -->
    <div id="menuToggle"><i class="icon-reorder"></i></div>
  </nav>


  
  <!-- ========== HEADER SECTION ========== -->
  <section id="home" name="home"></section>
  <div id="headerwrap">
    <div class="container">
      <div class="logo">
      <%= link_to image_tag("ditch.png"), root_path %>
      </div>

      <%= yield %>
        


        <div class="col-lg-6 col-lg-offset-3">
          
      </div>
    </div><!-- /container -->
  </div><!-- /headerwrap -->
  
  
  
    <!-- ========== CAROUSEL SECTION ========== --> 
  <section id="portfolio" name="portfolio"></section>
  <div id="f">
    <div class="container">
      <div class="row centered">
     
        <p class="centered"><i class="icon icon-circle"></i><i class="icon icon-circle"></i><i class="icon icon-circle"></i></p>
        

        <br>
        <br>
        
      </div><!-- row -->
    </div><!-- container -->
  </div>  <!-- f -->


 <%= javascript_include_tag "main" %>

</body>
</html>